In [12]:
import numpy as np
# link: https://www.machinelearningplus.com/python/101-numpy-exercises-python/?utm_content=cmp-true

In [13]:
# 1. Import numpy as np and see the version
print(np.__version__)

1.23.5


In [14]:
# 2. How to create a 1D array?
arr = np.arange(0, 10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
# 3. How to create a boolean array? 3x3 
arr = np.full((3, 3), True)
arr

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [17]:
# 4. How to extract items that satisfy a given condition from 1D array?
arr = np.arange(0, 10)
arr[arr %2 != 0]

array([1, 3, 5, 7, 9])

In [20]:
# 5. How to replace items that satisfy a condition with another value in numpy array?
arr[arr %2 != 0] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [31]:
# 6. How to replace items that satisfy a condition without affecting the original array?
arr = np.arange(0, 10)
arr_res = arr.copy()
arr_res[arr_res %2 != 0] = -1

print(arr_res)
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]
[0 1 2 3 4 5 6 7 8 9]


In [33]:
# 7. How to reshape an array?

np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [40]:
# 8. How to stack two arrays vertically?
a = np.arange(10).reshape(2, -1)
b = np.repeat(1, 10).reshape(2, -1)

res = np.vstack([a, b])
res

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [46]:
# 9. How to stack two arrays horizontally?
a = np.arange(10).reshape(2, -1)
b = np.repeat(1, 10).reshape(2, -1)

res = np.hstack([a, b])
res

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

### np._r 
let you to add up multiple array into one bigger one, like bellow

In [55]:
# 10. How to generate custom sequences in numpy without hardcoding?
a = np.array([1,2,3])

res = np.r_[ np.repeat(a, 3), np.tile(a, 3)]
res

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [74]:
# 11. How to get the common items between two python numpy arrays?
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])

#### np.interesct()

In [81]:
res = [np.append(res, i) for i in a if i in b]
res

np.intersect1d(a, b)

array([2, 4])

In [88]:
# 12. How to remove from one array those items that exist in another?
a = np.array( [1, 2, 3, 4, 5])
b = np.array( [5, 6, 7, 8, 9])

com = np.intersect1d(a, b)
a[a != com]

#OR BETTER 
np.setdiff1d(a, b)

array([1, 2, 3, 4])

In [89]:
# 13. How to get the positions where elements of two arrays match?

In [100]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

#### np.where()

In [103]:
np.where(a == b)

(array([1, 3, 5, 7]),)

In [105]:
# 14. How to extract all numbers between a given range from a numpy array?

a = np.array([2, 6, 1, 9, 10, 3, 27])

In [119]:
# Method 1
index = np.where((a >= 5) & (a <= 10))
a[index]

# Method 2:
index = np.where(np.logical_and(a>=5, a<=10))
a[index]
#> (array([6, 9, 10]),)

# My favorite!!
a[ (5 <= a) & (a <= 10)]

array([ 6,  9, 10])