In [2]:
import numpy as np

### Itroduction to creation of numpy array and basic operations

In [3]:
# Links used to learn:
# 1) https://www.youtube.com/watch?v=QUT1VHiLmmI&t=318s / YT - freecodecamp NUMPY
# 2) 
# 3)
# 4)

In [36]:
# How to initialize array
a = [1, 2, 3]
a = np.array([1, 2, 3], dtype = 'int16') # you can specify your data-type to be more efficient
a

array([1, 2, 3], dtype=int16)

In [37]:
b = np.array([[9.0, 8.0, 7.0],
             [6.0, 4.0, 5.0]])
b

array([[9., 8., 7.],
       [6., 4., 5.]])

In [38]:
#check the dimensions
f"a: {a.ndim}, b: {b.ndim}"

'a: 1, b: 2'

In [39]:
# check the shape  
# note: the shape will pass you tule (n of rows, n of columns)
f"a: {a.shape}, b: {b.shape}"

'a: (3,), b: (2, 3)'

In [40]:
# get type
f"a: {a.dtype}, b: {b.dtype}"

'a: int16, b: float64'

In [41]:
# get size
f"a: {a.itemsize}, b: {b.itemsize}" 

'a: 2, b: 8'


### Accessing/ Changing specific elements, rows, columns etc..

In [44]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [45]:
a.shape

(2, 7)

In [52]:
# Get a specific element [row idx, col idx]
a[1, 5] #13
a[-1, -2] #13      -you can also get negative indexing

13

In [57]:
# Get a specific row
a[0, ]

array([1, 2, 3, 4, 5, 6, 7])

In [59]:
# Get a specific column
a[ :,2]

array([ 3, 10])

In [64]:
# Getting litle fanncie [startindex:endindex:stepsize]
a[0, 1: 6: 2]

array([2, 4, 6])

In [67]:
# Change somethin in np.array 
a[1, 5] = 20
a

array([[ 1,  2,  5,  4,  5,  6,  7],
       [ 8,  9,  5, 11, 12, 20, 14]])

In [68]:
a[:, 2] = 5
a[:, 2] = [5, 5]
a

array([[ 1,  2,  5,  4,  5,  6,  7],
       [ 8,  9,  5, 11, 12, 20, 14]])

In [69]:
b = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [77]:
# A litle bit harder indexing
b[0, 1, 1]
b[:, 1, :]

array([[0, 0],
       [0, 0]])

In [76]:
# Changes in advanced indexing
b[:, 1, :] = [[0, 0], [0, 0]]
b

array([[[1, 2],
        [0, 0]],

       [[5, 6],
        [0, 0]]])

### Initializing Different Types of Arrays

In [80]:
# All 0s matrix
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [83]:
# All 1s matrix
np.ones((4, 3, 2), dtype='int32')

array([[[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]]], dtype=int32)

In [84]:
# Any other number
np.full((2, 2), 99, dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [87]:
# Any other number (full_like) -based on other structure. 
np.full(a.shape, 4)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [92]:
# Random decimal numbers
np.random.rand(4, 3, 3)
np.random.rand(4, 2)

array([[0.20062133, 0.15612716],
       [0.43318669, 0.6274685 ],
       [0.47726058, 0.88895678],
       [0.14593223, 0.93784823]])

In [94]:
# Random Integer Values
np.random.randint(7, size=(3, 3))

array([[3, 4, 3],
       [6, 2, 4],
       [2, 3, 1]])

In [99]:
# return the square matrix of 0, ones
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [103]:
arr = np.array([1, 2, 3])
r1 = np.repeat(arr, 3, axis=0)
r1

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [109]:
arr = np.array([[1, 2, 3]]) 
#to repeat multiple dim parameter you need to pass a multiple dimensions at this vector
r1 = np.repeat(arr, 3, axis=0)
r1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [110]:
arr = np.array([[1, 2, 3]]) 
#to repeat multiple dim parameter you need to pass a multiple dimensions at this vector
r1 = np.repeat(arr, 3, axis=1)
r1

array([[1, 1, 1, 2, 2, 2, 3, 3, 3]])

In [111]:
# create this array
np.array([
    [1, 1, 1, 1, 1],
    [1, 0, 0, 0, 1],
    [1, 0, 9, 0, 1],
    [1, 0, 0, 0, 1],
    [1, 1, 1, 1, 1]
])

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [140]:
# created in few lines
output = np.ones((5, 5))
z = np.zeros((3,3))
output[1:-1, 1:-1] = z
output[2, 2] = 9
output

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

### Be careful when copying arrays!!!

In [143]:
a = np.array([1, 2, 3])
b = a
a

array([1, 2, 3])

In [151]:
b[0] = 100
b

array([100,   2,   3])

In [149]:
# it changed a also
a

array([100,   2,   3])

### Mathematics

In [153]:
a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

In [154]:
a + 2

array([3, 4, 5, 6])

In [155]:
a - 2

array([-1,  0,  1,  2])

In [156]:
a * 2

array([2, 4, 6, 8])

In [157]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [158]:
a ** 2

array([ 1,  4,  9, 16])

In [159]:
a ** 0.5

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [161]:
b = np.array([1, 0, 1, 0])
b

array([1, 0, 1, 0])

In [163]:
a + b

array([2, 2, 4, 4])

In [168]:
# Take the sinus / cosinus of number etc..
np.sin(a) 
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

### Linear algebra 

In [171]:
a = np.ones((2,3))
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [176]:
b = np.full((3,2), 2)
b

array([[2, 2],
       [2, 2],
       [2, 2]])

In [ ]:
a * b
#ERROR

In [175]:
np.matmul(a, b) #matmul stands for matrix multiplier

array([[6., 6.],
       [6., 6.]])

In [180]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

In [181]:
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [182]:
x =np.array([1, 1, 1]) * np.array([0, 1, 0])
x

array([0, 1, 0])

In [183]:
## Referecne docs(https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix norm
# Inverse
# Etc..

### Statistics

In [184]:
stats = np.array([[1, 2, 3], [4, 5, 6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [187]:
print("Min:",  np.min(stats) )
print("Max:",  np.min(stats) )

Min: 1
Max: 1


In [192]:
print("Min:",  np.min(stats, axis=0) )

print("Max:",  np.max(stats, axis=1) )

Min: [1 2 3]
Max: [3 6]


In [193]:
np.sum(stats)

21

In [202]:
np.average(stats)
np.median(stats)

3.5

### Reorganize Arrays

In [210]:
before = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8]
])
print(before)
print(before.shape)

# to change the shape

after = before.reshape((2, 2, 2)) #The amount of values must be same with original one
after

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [211]:
# Vertically stacking vectors
v1 = np.array( [1, 2, 3, 4])
v2 = np.array( [5, 6, 7, 8])

np.vstack([v1, v2, v2, v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [217]:
# Horizontal stacking
h1 = np.ones( (2, 4))
h2 = np.zeros((2, 2))

np.hstack((h1, h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

### Miscellaneous

###### Load data from a file

In [245]:
filedata = np.genfromtxt('data/123datanumpy.txt', delimiter=',')
filedata = filedata.astype('int32')
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


### Boolean Masking and Advanced Indexing

In [236]:
filedata > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [237]:
filedata[filedata > 50] #return the index that meet the requirement

array([196,  75, 766,  75,  55, 999,  78,  76,  88], dtype=int32)

In [243]:
ar = np.arange(1, 10)
print(ar) 

ar[[1, 2, 8]]

[1 2 3 4 5 6 7 8 9]


array([2, 3, 9])

In [250]:
# Does any value in any of the column in filedata is greater than 50? 
print( np.any(filedata > 50, axis=0) )

print()
# Does all value in any of the column in filedata is greater than 50? 
print( np.all(filedata > 50, axis=0) )

[False False False False  True  True False  True  True False False False
 False False False False  True  True]

[False False False False  True False False False False False False False
 False False False False False False]


In [254]:
( ~((filedata > 50) & (filedata < 100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])