In [1]:
import numpy as np

In [2]:
q = np.array([23, 312, 233, 1, 5, 84, 2, 21, 163, 35, 531, 13])

In [3]:
q[q>100]

array([312, 233, 163, 531])

In [6]:
np.where(q>100)

(array([ 1,  2,  8, 10]),)

In [7]:
q[np.where(q>100)]

array([312, 233, 163, 531])

In [8]:
## Task 6
ans = np.array([1, 15, 4, 13, 8, 21, 3, 12, 11, 13, 11, 5, 32, 13, 0, 2]).reshape(4, 4)
ans

array([[ 1, 15,  4, 13],
       [ 8, 21,  3, 12],
       [11, 13, 11,  5],
       [32, 13,  0,  2]])

In [11]:
ans[1,2]

3

In [19]:
det = np.linalg.det(ans)
det

-19963.99999999999