In [2]:
import numpy as np
import sys

Few word about creation of matrix & vector. 

np.arange(_) - wiemy, z jakiego zakresu elementy chcemy, ewentualnie ich odstępy.
np.arange( 1, 110 + 1, 5) - dostaniemy wartości od 1 do 110 włącznie, ze skokami co 5

In [22]:
sample_vector_even = np.arange(1, 12+1, 2)
sample_vector

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

np.Linspace(_) - wiemy ile elementów chcemy i z jakiego zakresu
np.Linspace( 1, 10 +1, 3) - da nam 3 liczby od 1 do 10 włcznie z różnymi odstępami

In [20]:
np.linspace(1, 10, 3)

array([ 1. ,  5.5, 10. ])

In [23]:
sample_matrix = np.array([
    np.linspace(100, 333, 5),
    np.linspace(467, 874, 5),
    np.linspace(250, 550, 5)
])

sample_matrix

array([[100.  , 158.25, 216.5 , 274.75, 333.  ],
       [467.  , 568.75, 670.5 , 772.25, 874.  ],
       [250.  , 325.  , 400.  , 475.  , 550.  ]])

object.shape - gives us tuple, of shape of given matrix ( nuber of rows, number of columns )
object.size - gives us size of given object ( number of rows * number of columns )
object.ndim - gives us amount of dimensions of given object

In [31]:
sample_matrix.shape

(3, 5)

In [33]:
sample_vector.shape

(13,)

In [30]:
sample_matrix.size

15

In [34]:
sample_vector.size

13

In [32]:
sample_matrix.ndim 

2

How to get to specified elements? 

In [41]:
sample_matrix[2][3]

475.0

In [46]:
sample_matrix[:,2:]

array([[216.5 , 274.75, 333.  ],
       [670.5 , 772.25, 874.  ],
       [400.  , 475.  , 550.  ]])

Random functions in Numpy library

np.random.random(size =1) - generates random number from range 0, 1
np.random.norrmal(size = 1) - generuje losową liczbę z rozkładu normalnego 
np.random.uniform(size = 1) - generuje losową liczbę z rozkładu jednostajnego
np.random.randint(low, high, size) - generates pseudo random integer. #Given numbers may be repetitive.

In [53]:
np.random.random(3)

array([0.39814997, 0.50537573, 0.83933962])

In [58]:
sample_vector = np.array([20, 17, 67, 456, 100, 6, 12.5])
sample_vector

array([ 20. ,  17. ,  67. , 456. , 100. ,   6. ,  12.5])

In [60]:
sample_vector_greater_than_99 = np.where(sample_vector > 99)
sample_vector_greater_than_99

(array([3, 4]),)

In [ ]:
sample_vector[sample_vector_greater_than_99]

: 

In [ ]:
task_1_vector = np.arange(1, 9+1)
task_1_vector[::-1]

: 

In [88]:
vector_1 = np.array([1, 23, 4, 31, 1, 1, 4, 23, 4, 1])

np.unique(vector_1)

array([ 1,  4, 23, 31])

In [89]:
matrix_1 =np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

matrix_2 = np.array([
    [10, 10, 10],
    [20, 20, 20],
    [30, 30, 30]
])

In [93]:
np.add(matrix_1, matrix_2) #dodawanie macierzy

array([[11, 12, 13],
       [24, 25, 26],
       [37, 38, 39]])

In [96]:
np.subtract(matrix_1, matrix_2) #odejmowanie macierzy

array([[ -9,  -8,  -7],
       [-16, -15, -14],
       [-23, -22, -21]])

In [98]:
matrix_1 * matrix_2 #mnożenie macierzy

array([[ 10,  20,  30],
       [ 80, 100, 120],
       [210, 240, 270]])

In [100]:
matrix_1 * 10 #mnożenie macierzy przez skalar

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [102]:
matrix_1.T #Transpozycja macieży, Przekątna macierzy bez zmian 
# Jeśli w macierzy "i" to wiersze a "l" to kolumny odwrócicmy ze sobą kolumny z wierzami gdzie pierwszy, 
# ostatni i środkowy element macierzy zostają dzięki temu bez zmian. 

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [104]:
matrix_1.shape

(3, 3)

In [109]:
vector_from_matrix_1 = np.ndarray.flatten(matrix_1)
vector_from_matrix_1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [112]:
task_3_vector = np.arange(2, 10+1)
task_3 = np.reshape(task_3_vector, (3,3))
task_3

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [122]:
# BAD CODE:
# ls = []
# [ls.append(np.random.randint(10, 30+1)) for i in range(6)]
# task_4 = np.array(ls)
# task_4
# 
# Good CODE: 
task_4 = np.random.randint(10, 30, size = 6)
task_4 = np.reshape(task_4, (2,3))
task_4

array([[24, 20, 22],
       [13, 22, 17]])

In [132]:
# Task 5
task_5_sample = np.array([23, 45, 112, 150, 43, 254, 95, 8])
task_5_sample[np.where(task_5_sample > 100)]
task_5_sample

array([ 23,  45, 112, 150,  43, 254,  95,   8])

In [134]:
# Task 6
matrix = np.array([
    [1, 15, 4, 13],
    [8, 21, 3, 12],
    [11, 13, 11, 5],
    [32, 13, 0, 2]
])

second_row_third_column = matrix[1, 2]
second_row_third_column

3

In [139]:
matrix.max()

32

In [140]:
matrix.min()

0

In [145]:
matrix.diagonal().sum()

35