### Statistics

In [1]:
Watch scipy.stats library cuz it contatins many probability distribution
- Berlouniego ( Poissona ) 
- Wielomianowy ( Dwumianowy, Binomial)
- Normalny ( Gaussa )
- t-Studenta

Pojęcia: 
    - Mediana
    - Średnia
    - Odchylenie standardowe i wariancja
    - Korelacja
    - Kowariancja
    - Oczekiwana średnia / szanse na wygraną * możliwa wygrana. 

Statystyki opisowe! Konieczne jest zapoznanie się porządne z tematem.

In [1]:
import numpy as np
import scipy as sc

In [6]:
sample_matrix = np.array([
    [1, 15, 4, 10],
    [13, 15, 19, -10],
    [13, 155, 11, 15],
    [16, 16, 61, 16],
    ])

In [8]:
sample_matrix

array([[  1,  15,   4,  10],
       [ 13,  15,  19, -10],
       [ 13, 155,  11,  15],
       [ 16,  16,  61,  16]])

In [13]:
#średnia
np.mean(sample_matrix)

23.125

In [15]:
#mediana
np.median(sample_matrix)

15.0

In [16]:
sample_matrix = np.array([[  1,  15,   4,  10],
       [ 13,  15,  19, -10],
       [ 13, 155,  11,  15],
       [ 16,  16,  61,  16]])

In [17]:
np.std(sample_matrix)

36.801621907193166

In [20]:
[print(a) for a in sample_matrix]

[ 1 15  4 10]
[ 13  15  19 -10]
[ 13 155  11  15]
[16 16 61 16]


[None, None, None, None]

In [37]:
arr = np.random.randint(1, 100, 30).reshape(6, 5)

In [38]:
arr # oryginalne arr 

array([[75, 33,  1, 89,  1],
       [15, 83, 46, 91, 96],
       [39, 29, 16, 23, 38],
       [ 3, 35,  6, 95, 40],
       [ 8, 62, 26, 41, 67],
       [82, 31, 36, 13, 11]])

Normalizacja wartości w datasecie 

In [39]:
arr = (arr - arr.mean() / arr.std())
arr # znormalizowany arr

array([[73.64132422, 31.64132422, -0.35867578, 87.64132422, -0.35867578],
       [13.64132422, 81.64132422, 44.64132422, 89.64132422, 94.64132422],
       [37.64132422, 27.64132422, 14.64132422, 21.64132422, 36.64132422],
       [ 1.64132422, 33.64132422,  4.64132422, 93.64132422, 38.64132422],
       [ 6.64132422, 60.64132422, 24.64132422, 39.64132422, 65.64132422],
       [80.64132422, 29.64132422, 34.64132422, 11.64132422,  9.64132422]])

In [61]:
arr_1 = np.random.randint(1, 100, 4).reshape(2, 2)
arr_2 = np.random.randint(1, 100, 4).reshape(2, 2)

In [62]:
res = sum(( arr_1 - arr_2) ** 2) **0.5
res

array([77.41446893, 91.58602513])

In [63]:
f = lambda x, y: np.sqrt(sum((x - y) **2))
f(arr_1, arr_2)

array([77.41446893, 91.58602513])

Above functions of euklidian distance

In [2]:
import scipy.stats as scs

## Hypotesis testing

In [13]:
import numpy as np
import scipy.stats as scs

In [33]:
data_1 = [5.01, 5.02, 5.00, 4.99, 4.96]
data_2 = [0.97, 1.01, 1.02, 8.00, 2.99]
data_3 = np.array(sorted(data_1))

data_4 = np.arange(1, 1515, 5)
data_5 = np.random.normal(size = 1000)

data_1 = np.array(data_1)
data_2 = np.array(data_2)

print(data_1.mean(), data_2.mean())

4.996 2.798


In [16]:
# stats.ttest_1samp() - find P-value -> probability of similarity
scs.ttest_1samp(data_1, popmean=5)

TtestResult(statistic=-0.3885143449428653, pvalue=0.7174283599145157, df=4)

In [18]:
scs.ttest_1samp(data_2, popmean=5)

TtestResult(statistic=-1.623391521731075, pvalue=0.17982775482279942, df=4)

In [22]:
scs.ttest_ind(data_1, data_2)

Ttest_indResult(statistic=1.6203959046657326, pvalue=0.14380620673076863)

In [26]:
scs.ttest_ind(data_1, data_3)

Ttest_indResult(statistic=0.0, pvalue=1.0)

In [31]:
# Sprawdzanie, czy dane są z rozkładu normalnego 
scs.normaltest(data_4)

# Jeśli p-value w teście normalnym jest bardzo niskie np. niże od 0.005
#, to odrzucamy Hipoteze zerową, która mówi, że jest to rozkład normalny.

NormaltestResult(statistic=165.16651401966465, pvalue=1.363161096000046e-36)

In [38]:
scs.normaltest(data_5)

# Jeśli p-value w teście normalnym, jest wyższe niż 0.05, możemy uznać, że jest to rozkład normalny.

NormaltestResult(statistic=3.0391764785165925, pvalue=0.2188019624645129)

In [ ]:
Przykłady testów: 
    - Test Shapiro Wilka - bardziej konserwatywny test na rozkład normalny
    - Test Równości wariancji
    Do testów minimum 30 obserwacji (są to testy deterministyczne, dają ten sam wynik dla tych samych danych)

In [ ]:
# ZADANIE 10: 
#    - Do ogarnięcia w domu

### Probability