In [1]:
import numpy as np

In [4]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [5]:
y = np.random.randint(2, 6, (2, 3))
y

array([[2, 4, 4],
       [2, 3, 4]])

In [6]:
z = np.array([[1, 2, 3], [1, 2, 3]])
z

array([[1, 2, 3],
       [1, 2, 3]])